sass:
    style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Dal Voordeel Bestellen | NS"
  - scope:
      path: "pages"
    values:
      progress: true