progress:
  step1: Gegevens
  step2: Bestellen
  step3: Betalen
  step4: Bedankt


comfort:
- icon: counter--large
  description: Je betaalt de abonnementskosten voor het eerste jaar aan het einde van uw bestelling. Na het eerste jaar worden de abonnementskosten jaarlijks van je rekening afgeschreven, via automatische incasso.
- icon: ov-chipkaart--large
  description: Je krijgt gratis een nieuwe persoonlijke OV&#8209;chipkaart bij de bestelling van een jaarabonnement. Binnen 1 week ontvang je de OV&#8209;chipkaart, mét het abonnement er op, in huis.
- icon: train--medium
  description: Betalen kan snel, veilig en via uw eigen bank met iDeal. Je betaalt de abonnementskosten voor het eerste jaar aan het einde van je bestelling.


banks:
- title: ABN AMRO
  icon: abn
- title: ASN Bank
  icon: asn
- title: bunq
  icon: bunq
- title: Handelsbanken
  icon: handelsbanken
- title: ING
  icon: ing
- title: Knab
  icon: knab
- title: Moneyou
  icon: moneyou
- title: Rabobank
  icon: rabobank
- title: RegioBank
  icon: regiobank
- title: SNS
  icon: sns
- title: Triodos Bank
  icon: triodos
- title: van Lanschot
  icon: lanschot


thanks:
- icon: mail
  copy: "Je ontvangt een bevestiging op <blue class='js-customer-data' id='email'>maartendevries@gmail.com</blue>"
- icon: ov-chipkaart
  copy: "Binnen <blue>7 dagen</blue> wordt je OV&#8209;chipkaart opgestuurd naar Jan van Galenstraat 56. Je kunt dan meteen gebruik maken van jouw abonnement."
  # copy: "Binnen <blue>1 uur</blue> kun je met je OV&#8209;Chipkaart (3528 1865 9452 0045) jouw bestelling ophalen bij een NS&#8209;kaartautomaat. Daarna kan je er direct mee reizen."
- icon: user
  copy: "Je <blue>NS-account</blue> staat klaar om geactiveerd te worden. Je ontvangt daar zometeen een aparte e-mail over."
- icon: invoice
  copy: "Je hebt betaald voor <blue>1 jaar</blue>. Na deze periode wordt het bedrag automatisch van jouw bankrekening afgeschreven."
