progress:
  step1: Gegevens
  step2: Bestellen
  step3: Betalen
  step4: Bedankt


comfort:
- icon: counter--large
  description: U betaalt de abonnementskosten voor het eerste jaar aan het einde van uw bestelling. Na het eerste jaar worden de abonnementskosten jaarlijks van uw rekening afgeschreven, via automatische incasso.
- icon: ov-chipkaart--large
  description: U krijgt gratis een nieuwe persoonlijke OV-chipkaart bij uw bestelling van een jaarabonnement. Binnen 1 week ontvangt u de OV-chipkaart, mét het abonnement er op, in huis.
- icon: train--medium
  description: Betalen kan snel, veilig en via uw eigen bank met iDeal. U betaalt de abonnementskosten voor het eerste jaar aan het einde van uw bestelling.


banks:
- title: ABN AMRO
  icon: abn
- title: ASN Bank
  icon: asn
- title: bunq
  icon: bunq
- title: Handelsbanken
  icon: handelsbanken
- title: ING
  icon: ing
- title: Knab
  icon: knab
- title: Moneyou
  icon: moneyou
- title: Rabobank
  icon: rabobank
- title: RegioBank
  icon: regiobank
- title: SNS
  icon: sns
- title: Triodos Bank
  icon: triodos
- title: van Lanschot
  icon: lanschot


thanks:
- icon: mail
  copy: "Je ontvangt een bevestiging op <b>maartendevries@gmail.com</b>"
- icon: ov-chipkaart
  copy: "Binnen <b>7 dagen</b> wordt je OV&#8209;chipkaart opgestuurd."
- icon: user
  copy: "Je <b>NS-account</b> staat klaar om geactiveerd te worden. Je ontvangt daar zometeen een aparte e-mail over."
- icon: chat
  copy: "Vragen? Kijk dan op het <a>NS Serviceforum</a> of bel ons op <a>030 751 51 55.</a>"
