price:
  dvd: € 4,34
  kd: € 25,50


progress:
  step1: Gegevens
  step2: Bestellen
  step3: Betalen
  step4: Bedankt


comfort:
- icon: ov-chipkaart--large
  description: "Nieuwe persoonlijke OV&#8209;chipkaart nodig? Ontvang gratis bij de bestelling van een jaarabonnement. <br><b class='dib mt-2 f-red'>Let op:</b> We hebben tijdens het bestellen een foto van je nodig voor op de kaart."
- icon: subscription--large
  description: Heb je al een persoonlijke OV&#8209;chipkaart met foto? Voer dan tijdens het bestellen je kaartnummer in. Je abonnement kun je binnen een uur na het betalen van je bestelling ophalen bij een NS-kaartautomaat.
- icon: euro--medium
  description: Je betaalt de abonnementskosten voor het eerste jaar aan het einde van uw bestelling. Na het eerste jaar worden de abonnementskosten jaarlijks van je rekening afgeschreven, via automatische incasso.


banks:
- title: ABN AMRO
  icon: abn
- title: ASN Bank
  icon: asn
- title: bunq
  icon: bunq
- title: Handelsbanken
  icon: handelsbanken
- title: ING
  icon: ing
- title: Knab
  icon: knab
- title: Moneyou
  icon: moneyou
- title: Rabobank
  icon: rabobank
- title: RegioBank
  icon: regiobank
- title: SNS
  icon: sns
- title: Triodos Bank
  icon: triodos
- title: van Lanschot
  icon: lanschot


thanks:
- icon: mail
  copy: "Je ontvangt een bevestiging van je bestelling op <blue class='js-customer-data' id='email'>maartendevries@gmail.com</blue>."
- icon: ov-chipkaart
  copy: "Je ontvangt een e&#8209;mail wanneer je jouw bestelling kunt <blue>ophalen bij een NS kaartautomaat</blue>, met OV-Chipkaart 3528 2565 1121 9854."
- icon: user
  copy: "De ingangsdatum van je abonnement is <blue>1 december 2019</blue>"
- icon: invoice
  copy: "Je hebt betaald voor <blue>1 maand</blue>. Hierna wordt maandelijks € 4,34 van jouw bankrekening afgeschreven."
