checkbox:
- title: Keuzedagen 2e klas
  description: 7 vrije reisdagen voor 60+
  price: € 49,00
  per: / jaar

- title: OV-fiets
  description: Huur een fiets en betaal automatisch via je bankrekening

- title: Stallen op Rekening
  description: Veilig uw fiets stallen en achteraf betalen

# - title: IC Direct Altijd Toeslagvrij
#   description: Onbeperkt reizen op het gehele traject van de Intercity Direct
#   price: € 51,00
#   per: / mnd